version: 3

vars:
  DEV_ENV_FILE: "build/configs/envs/.env.dev"
  DEV_DOCKER_COMPOSE_PATH: "build/compose-dev.yaml"

  PROD_ENV_FILE: "build/configs/envs/.env.prod"
  PROD_DOCKER_COMPOSE_PATH: "build/compose.yaml"

  TEST_ENV_FILE: "build/configs/envs/.env.test"
  TEST_DOCKER_COMPOSE_PATH: "build/compose-test.yaml"

tasks:
  # LOCAL
  run:
    desc: Run app
    cmds:
      - "go run cmd/main.go"

  build:
    desc: Build app
    cmds:
      - go build -o bin/main cmd/main.go
  # END

  # UTILS
  doc:
    desc: Generate docs
    cmds:
      - swag fmt
      - swag init -g ./cmd/main.go -o ./api/rest/v1 --parseDependency  --parseInternal

  lint:
    desc: Lint app
    cmds:
      - "golangci-lint run --fix"

  pb:
    desc: Gen Proto file
    cmds:
      - "protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative api/grpc/v1/gen/app.proto"

  mocks:
    desc: Generate mocks
    cmds:
      - mockgen -source="./internal/ctrl/ctrl.go" -destination="tests/mocks/mock_ctrl.go" -package=mocks
  # END

  # DOCKER
  dc-prod:
    desc: Run prod compose
    cmds:
      - "docker compose --env-file {{.PROD_ENV_FILE}} -f {{.PROD_DOCKER_COMPOSE_PATH}} up --watch"

  dc-dev:
    desc: Run dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_FILE}} -f {{.DEV_DOCKER_COMPOSE_PATH}} up --watch"

  dc-dev-build:
    desc: Run dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_FILE}} -f {{.DEV_DOCKER_COMPOSE_PATH}} up --build --watch"

  dc-dev-down:
    desc: Shutdown dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_FILE}} -f {{.DEV_DOCKER_COMPOSE_PATH}} down"

  dc-test:
    desc: Run integration tests helper containers
    cmds:
      - "docker compose --env-file {{.TEST_ENV_FILE}} -f {{.TEST_DOCKER_COMPOSE_PATH}} up"

  dc-test-down:
    desc: Shutdown integration tests helper containers
    cmds:
      - "docker compose -f {{.TEST_DOCKER_COMPOSE_PATH}} down"

  k-up:
    desc: Run k8s manifests
    cmds:
      - "kubectl apply -f build/k8s/cfg/cfg.yaml"
      - "kubectl apply -f build/k8s/cfg/secret.yaml"
      - "kubectl apply -f build/k8s/svc.yaml"
      - "kubectl apply -f build/k8s/deploy.yaml"

  k-down:
    desc: Remove k8s manifests
    cmds:
      - "kubectl delete -f build/k8s/cfg/cfg.yaml"
      - "kubectl delete -f build/k8s/cfg/secret.yaml"
      - "kubectl delete -f build/k8s/svc.yaml"
      - "kubectl delete -f build/k8s/deploy.yaml"
  # END

  # TESTS
  t:
    desc: Run tests
    cmds:
      - "task t-hdl"
      - "task t-ctrl"
      - "task t-repo"
      - "task t-integ"

  t-hdl:
    desc: Test handlers
    cmds:
      - "task t-http"
      - "task t-grpc"

  t-http:
    desc: Test http handlers
    cmds:
      - "go test ./internal/hdl/http"
      - "go test -coverprofile=cov_http.out ./internal/hdl/http && go tool cover -func=cov_http.out"

  t-grpc:
    desc: Test grpc handlers
    cmds:
      - "go test ./internal/hdl/grpc"
      - "go test -coverprofile=cov_grpc.out ./internal/hdl/grpc && go tool cover -func=cov_grpc.out"

  t-ctrl:
    desc: Run ctrl tests
    cmds:
      - "go test ./internal/ctrl"
      - "go test -coverprofile=cov_ctrl.out ./internal/ctrl && go tool cover -func=cov_ctrl.out"

  t-repo:
    desc: Run repo tests
    cmds:
      - "go test ./internal/repo/db"
      - "go test -coverprofile=cov_repo.out ./internal/repo/db && go tool cover -func=cov_repo.out"

  t-integ:
    desc: Run integration tests
    cmds:
      - "go test -v ./tests/E2E/..."
  # END